// Copyright 2024 QMK
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#define DEBOUNCE 5

#define SPLIT_TRANSACTION_IDS_KB SYNC_JOYSTICK_TR_ID
// Shared memory
//#define SPLIT_TRANSPORT_MIRROR --> keyboard.json split.transport.sync.matrix_state
//#define SPLIT_USER_STATE_SIZE sizeof(joystick_state)

//#define SPLIT_ACTIVITY_ENABLE
//#define POINTING_DEVICE_COMBINED
#define SPLIT_POINTING_ENABLE
#define POINTING_DEVICE_RIGHT
#define POINTING_DEVICE_GESTURES_SCROLL_ENABLE
#define TRACKPAD_ENABLE
//#define TRACKBALL_ENABLE

// === Trackpad
#ifdef TRACKPAD_ENABLE
#define AZOTEQ_IQS5XX_TPS43
#define AZOTEQ_IQS5XX_ROTATION_270
#define AZOTEQ_IQS5XX_TAP_ENABLE true
#define AZOTEQ_IQS5XX_TWO_FINGER_TAP_ENABLE true
#define AZOTEQ_IQS5XX_PRESS_AND_HOLD_ENABLE true
//#define AZOTEQ_IQS5XX_ZOOM_ENABLE
#define AZOTEQ_IQS5XX_SCROLL_ENABLE true
//#define CIRQUE_PINNACLE_DIAMETER_MM 35
//#define CIRQUE_PINNACLE_TAP_ENABLE
//#define CIRQUE_PINNACLE_CURVED_OVERLAY
//#define CIRQUE_PINNACLE_SECONDARY_TAP_ENABLE

#define I2C_DRIVER I2CD1
#define I2C1_SDA_PIN GP10
#define I2C1_SCL_PIN GP11
#endif // TRACKPAD_ENABLE

// === Trackball ===
#ifdef TRACKBALL_ENABLE
#define SPI_DRIVER SPID1
#define SPI_SCK_PIN GP10
#define SPI_MOSI_PIN GP11
#define SPI_MISO_PIN GP12
#define PMW33XX_CS_PIN GP13

/* Optional. */
#define PMW33XX_CPI 1600      // The CPI range is 100-12000, in increments of 100. Defaults to 1600 CPI.
#define PMW33XX_CLOCK_SPEED 2000000 // Sets the clock speed that the sensor runs at. Defaults to 2000000
#define MOUSE_EXTENDED_REPORT // Use -32767 to 32767, instead of just -127 to 127.

#define POINTING_DEVICE_ROTATION_90
#define POINTING_DEVICE_INVERT_X
//#define POINTING_DEVICE_INVERT_Y
#endif // TRACKBALL_ENABLE

// Split driver = vendor
#define SERIAL_PIO_USE_PIO0
#define SERIAL_USART_FULL_DUPLEX
#define SERIAL_USART_RX_PIN GP1
#define SERIAL_USART_TX_PIN GP0

// RP2040- and hardware-specific config
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET // Activates the double-tap behavior
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 500U
#define PICO_XOSC_STARTUP_DELAY_MULTIPLIER 64

#define CUSTOM_JOYSTICK_ENABLE
#define JOYSTICK_LEFT

// Min 0, max 6: X, Y, Z, Rx, Ry, Rz
#ifdef CUSTOM_JOYSTICK_ENABLE
  #define JOYSTICK_AXIS_COUNT 2
  #define JOYSTICK_AXIS_X_PIN GP29
  #define JOYSTICK_AXIS_Y_PIN GP28
  //#define JOYSTICK_INVERT_X_AXIS
  #define JOYSTICK_INVERT_Y_AXIS
  // Min 8, max 16
  #define JOYSTICK_AXIS_RESOLUTION 10
  // Min 0, max 32
  #define JOYSTICK_BUTTON_COUNT 1
  #define JOYSTICK_BUTTON_PIN GP11
#endif
